name: Supabase CLI Action
description: Setup Supabase CLI, supabase, on GitHub Actions runners
author: Supabase
inputs:
  version:
    description: Version of Supabase CLI to install
    required: false
    default: 1.28.0
runs:
  using: node16
  main: dist/index.js
