name: My Workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1.3.0
        with:
          version: 1.136.3
      - name: Run Supabase CLI command
        run: supabase db migrate
